### PR TITLE
Bump version to 0.6.0

### PR DESCRIPTION
**Pull request by echarles**
Bump version to 0.6.0 to prepare the next release.

### CODE REVIEW

**Comment by juhasch** [comment]
Thank you for the PR!

**Comment by echarles** [comment]
Thx @juhasch 🙏 

I let you further cut the release. Ping me for anything.

**Comment by juhasch** [comment]
@echarles your help very much appreciated.
I guess I will do a 0.6.1 due to PR #144 and will upload it to PyPi then. I also need write permissions on conda-forge to update the feedstock, as I don't have them right now.

**Comment by echarles** [comment]
> I also need write permissions on conda-forge to update the feedstock, as I don't have them right now.

@bollwyvl may help for this.

**Comment by bollwyvl** [comment]
With any luck, the bot should pick it up in a few hours... Anybody can make
a PR, though!

**Comment by juhasch** [comment]
Hi @bollwyvl 
can you help me check what is going on the two repos:
1. <https://github.com/conda-forge/jupyter_contrib_core-feedstock>
Does not seem to create a PR automatically. Not sure how to trigger it.
2. <https://github.com/conda-forge/jupyter_nbextensions_configurator-feedstock>
There is a PR, but the assigned reviewers did not review it. I have no permissions to do so.

**Pull request merged**
