### PR TITLE
allow utf8 char in yml

### PR DESCRIPTION
**Pull request by haobibo**
Use codecs to open yaml file, so that UTF8 char in yaml file can be read properly.

### CODE REVIEW

**Comment by jcb91** [comment]
Thanks @haobibo, looks like a good plan, but some of the CI builds are failing at the moment, so it may take me a while to fix them first :expressionless:

**Comment by haobibo** [comment]
no problem~

**Comment by jcb91** [comment]
ok, CI stuff is fixed now, I think. Could we use `io.open`, rather than `codecs.open`? (I note on the codecs description that io.open is the preferred method). Also, if you could rebase this onto master, then hopefully all the CI builds should work again :)

**Comment by jcb91** [comment]
this looks now to be a rebased version merged with the original version?

**Pull request closed without merging**
