### PR TITLE
notebook v7 compatibility

### LINKED ISSUE #165: jupyter_nbextensions_configurator is not compatible with notebook 7.0.0
I have this exception when i run `jupyter nbextensions_configurator enable --sys-prefix`

```
Traceback (most recent call last):
  File "/home/alaa/code/test_env/test/bin/jupyter-nbextensions_configurator", line 5, in <module>
    from jupyter_nbextensions_configurator.application import main
  File "/home/alaa/code/test_env/test/lib/python3.10/site-packages/jupyter_nbextensions_configurator/__init__.py", line 18, in <module>
    from notebook.base.handlers import APIHandler, IPythonHandler
ModuleNotFoundError: No module named 'notebook.base'
```

### PR DESCRIPTION
**Pull request by dotlambda**
fixes #165

### CODE REVIEW

**Comment by divyabiyani** [comment]
@dotlambda, What is the plan to merge and release this changes?

**Comment by RRosio** [comment]
Thank you @dotlambda for opening this. Looks good, I will merge and plan for a release! It seems like there are a few more steps to take in order to get `jupyter_nbextensions_configurator` working with `NbClassic`, which will be the way to use it once someone migrates to Notebook 7.

**Comment by ecederstrand** [comment]
@RRosio Any updates on a new release for this package?

**Comment by RRosio** [comment]
@ecederstrand I apologize for the delay in my reply, the latest release is out: https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator/releases/tag/0.6.4. Please let me know if there is anything else I should take a look at/missed!

**Comment by astrowonk** [comment]
@RRosio FYI, 0.6.4 in [not available in conda-forge](https://anaconda.org/conda-forge/jupyter_nbextensions_configurator), thought the read me suggests installing from conda-forge.

For others who find this page but are still having issues even after 0.6.4, I had to run the steps at the bottom of [the known issues here](https://nbclassic.readthedocs.io/en/latest/nbclassic_dev_faq.html#known-issues):

```
jupyter nbclassic-extension install --sys-prefix --py jupyter_nbextensions_configurator --overwrite
jupyter nbclassic-extension enable --sys-prefix --py jupyter_nbextensions_configurator
jupyter nbclassic-serverextension enable --sys-prefix --py jupyter_nbextensions_configurator
```

to get the extension configurator to work with nbclassic.

**Pull request merged**
